spring:
  application:
    name: hello-spring-cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zch2017lrf/spring-cloud-config
          search-paths: respo
          username: zch2017lrf
          password: wdmzbjlrf130hui

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/